### ISSUE TITLE
Fennel support?

### ISSUE THREAD

**Issue by cata0309** [Benjamin-Dobell/IntelliJ-Luanalysis#101]
As @noncom pointed out in the original project.

> How do you think, is it possible to add Fennel (https://fennel-lang.org/) support to EmmyLua?
> 
> Fennel is a small Clojure-inspired LISP dialect for Lua and it would be really awesome to have support for it on the IDEA platform, at least syntax highlighting, even without any advanced features. I think that EmmyLua would be a perfect way to work with both Lua and Fennel.

**Comment by Benjamin-Dobell** [comment]
Unfortunately, no.

It wouldn't just be a matter of implementing Fennel's syntax, is appears the semantics are quite different. In this regard it's not really any different than how Java and Kotlin both run in the JVM, but they each require their own tooling/IDEs.
