### ISSUE TITLE
Disable unused parameter warnings on def files

### ISSUE THREAD

**Issue by Xseba360** [Benjamin-Dobell/IntelliJ-Luanalysis#129]
## Environment

Name | Version
-----|--------
IDEA version | Webstorm 2022.1.1
Luanalysis version | 1a78ef5e35086bd67dd4f1ba95f15a3e0568b547
OS | Windows 10 21H2
 
 
### Lua

Name | Setting  
-----|--------
Language level | Lua 5.4

### Type Safety

Name | Setting
-----|--------
Strict nil checks | ❎
Unknown type (any) is indexable | ☑️
Unknown type (any) is callabale | ☑️

## What are the steps to reproduce this issue?

1. Create a file with definitions (`filename.def.lua`)
2. Write function definitions

## What happens?
Unused parameter inspection appears

## What were you expecting to happen?
Since it's a definition file, and it's not supposed to be included/executed and should only serve as an information for the IDE, this inspection should not appear on `.def.lua` files.

## Any logs, error output, etc?
![image](https://user-images.githubusercontent.com/2056636/172031936-c4e8b9ae-5293-41ca-81d0-9d0401bd08bf.png)

**Comment by Benjamin-Dobell** [comment]
Closed by 7806d0fb1d34d37248cb6923c2c008873da48991
