### ISSUE TITLE
Stackoverflow while inferring types

### ISSUE THREAD

**Issue by dcorbin** [Benjamin-Dobell/IntelliJ-Luanalysis#13]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | 2020.2
 Luanalysis version | 1.0.3-IDEA201
 OS                        |MacOS 10.15.6

What are the steps to reproduce this issue?
------------------------------------------------
Analyze the tableEqualty.lua found here
https://gist.github.com/dcorbin/2b783571732ebf3d38c4975581dfe822

What happens?
-------------
Stackoverflow

What were you expecting to happen?
-----------------------------------------
Not an exception

Any logs, error output, etc?
------------------------------
Two stack traces included in the above GIST

Any other comments?
------------------------
If you can detect the infinite loop and abort with more information, perhaps I can provide small reproducing sample.

**Comment by Benjamin-Dobell** [comment]
I believe these issues are resolved on master. If not, please let me know.
