### ISSUE TITLE
Union function-types are not working as expecting

### ISSUE THREAD

**Issue by dvilker** [Benjamin-Dobell/IntelliJ-Luanalysis#135]
## Environment

Name | Version
-----|--------
IDEA version | Build #IU-213.7172.25, built on March 15, 2022
Luanalysis version | 1.2.2-IDEA203
OS | macOS 12.1 (21C52) 
 
## Preferences

(Preferences -> Languages & Frameworks > Luanalysis)

### Lua

Name | Setting  
-----|--------
Language level | 5.2

### Type Safety

Name | Setting
-----|--------
Strict nil checks | ☑️ / ❎ - no affecting
Unknown type (any) is indexable | ☑️
Unknown type (any) is callabale | ☑️

## What are the steps to reproduce this issue?
```
---@alias f1 fun(a: string)
---@alias f2 fun(a: string, b: number)

---@type f1|f2
local foo

foo("one", 1)
foo("one") -- "Missing argument: b: number"


---@type f2|f1
local bar

bar("one", 1)
bar("one") -- "Missing argument: b: number" too
```

## What happens?
IDE says missing argument.

## What were you expecting to happen?
IDE accepts both function types

**Comment by Benjamin-Dobell** [comment]
Sorry, just saw this. The reported error is correct. It is not safe to call `foo` with just one argument. If the variable held is of type `f2` then the second parameter is mandatory,

It sounds like you're actually trying to define one function type where the second parameter is optional. Thing can be achieved with overloads.

```lua
---@shape Foo
---@overload fun(a: string)
---@overload fun(a: string, b: number)

---@type Foo
local foo

foo("one", 1)
foo("one")
```
