### ISSUE TITLE
basic Lua 5.4 support

### ISSUE THREAD

**Issue by belm0** [Benjamin-Dobell/IntelliJ-Luanalysis#20]
Even if the plugin doesn't understand new 5.4 features, it would be helpful to at least ignore new syntax like local variable attributes (`<const>` and `<close>`).

**Comment by belm0** [comment]
Specifically for `local` attributes, for now I'd just like the attribute to be ignored so I can use the plugin normally.

[Lua 5.3](https://www.lua.org/manual/5.3/manual.html#3.3.7):
```
stat ::= local namelist [‘=’ explist]
```

[Lua 5.4](https://www.lua.org/manual/5.4/manual.html#3.3.7):
```
stat ::= local attnamelist [‘=’ explist]
attnamelist ::=  Name attrib {‘,’ Name attrib}
attrib ::= [‘<’ Name ‘>’]
```

Corresponding section of the plugin bnf:

https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/blob/master/src/main/java/com/tang/intellij/lua/lua.bnf#L340-L353

Perhaps the attributes could be ignored without affecting any code, as follows:
```
// TODO: proper Lua 5.4 variable attribute support
nameList ::= nameDef ('<' ('const'|'close') '>')? (',' nameDef ('<' ('const'|'close') '>')?)* {
    stubClass = "com.tang.intellij.lua.stubs.LuaPlaceholderStub"
}
```

**Comment by adriweb** [comment]
Upstream now has a commit for that: https://github.com/EmmyLua/IntelliJ-EmmyLua/commit/2dba6e9a77c62ba1b28eafc03ad8d83d65c6d91a

(Is a rebase/merge from upstream here considered? I saw a few commits fixing some things lately)
