### ISSUE TITLE
Bracketed-name fields shown as .null by docs

### ISSUE THREAD

**Issue by Lyrth** [Benjamin-Dobell/IntelliJ-Luanalysis#27]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | IdeaIU 2020.3
 Luanalysis version | 1.2.1-IDEA203
 OS                        | Win7

What are the steps to reproduce this issue?
------------------------------------------------
1. Create a class/shape with bracketed field names, e.g.:
![image](https://user-images.githubusercontent.com/38674984/103343294-bb393280-4ac6-11eb-9b6c-369a051f2b6f.png)
2. With the sample shape above, try to index members (and assign to them) through an instance of the class/shape, through brackets or dot notation (if possible), then hover over the indexer (example in "What happens?" section)
3. Additionally, type `a.` on a new line and look at the suggestions.

What happens?
-------------
2: Bracketed fields show as `.null`
![image](https://user-images.githubusercontent.com/38674984/103343821-e5d7bb00-4ac7-11eb-8a46-ce11f7570209.png)
![H21AZvY](https://user-images.githubusercontent.com/38674984/103343826-ea03d880-4ac7-11eb-86e4-eade2e448997.png)
(Field `m` is correct when hovered, both by doing `a.m` and `a["m"]`: shows `Test.m`)

3: The bracketed fields aren't being suggested
![image](https://user-images.githubusercontent.com/38674984/103343873-0dc71e80-4ac8-11eb-8707-68ad7fb4fe70.png)

What were you expecting to happen?
-----------------------------------------
For 2, should show the field names normally: treating the `n` field as `Test.n`, and others as `Test[1]`, `Test[true]`, etc.
For 3, it should at least include `n`; better if it'd also suggest the non-string-name fields.

Any logs, error output, etc?
------------------------------
None

Any other comments?
------------------------
Also, field description is placed too near to the left edge of the tooltip, don't know if it's normal.

**Comment by Benjamin-Dobell** [comment]
The primary issue identified is resolved by https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/commit/2a48c29abed5d0438b14b0591dc25872bde23214

I've opened a separate issue (#28) to track completion of (primitive) indexed field.
