### ISSUE TITLE
How to support the development?

### ISSUE THREAD

**Issue by adriweb** [Benjamin-Dobell/IntelliJ-Luanalysis#36]
This time, not a bug report or a feature request, but a question about the project: are you open to donations, or is there any "standard" way to support the project and its development/developer, if not financially? :)

Side-question: I see some commits still being done upstream (emmylua) - any plan to cherry-pick those (at least what's still doable of course)

**Comment by Benjamin-Dobell** [comment]
At this time I'm not really taking donations for this project in particular. If it gets more popular I suppose I could setup Github sponsorship.

For now the best way to contribute is via code contributions. If it's anything other than a small bug fix then opening an issue and having a discussion first would be best.

> Side-question: I see some commits still being done upstream (emmylua) - any plan to cherry-pick those (at least what's still doable of course)

The code-base has certainly diverged much more than I ever intended. So it's unlikely upstream patches will apply cleanly. If you come across a commit that specifically addresses some pain point your bumping up against, please open an issue here referring to EmmyLua commit and I'll take a look at what needs to be done.

**Comment by Benjamin-Dobell** [comment]
I've _finally_ finished setting up [my Github Sponsor profile](https://github.com/sponsors/Benjamin-Dobell). I was actually approved for Github Sponsors all the way back when it was in closed beta. Fortunately, according to the banner on my profile, I'm actually still eligible for Github's [Sponsors Matching Fund](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors#about-the-github-sponsors-matching-fund). So, if received in the next 12 months, Github will match the first $5000. Not too shabby. 

Closed by https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/commit/1c2c9cb85b8abce0fd576162e1cde470e797be36
