### ISSUE TITLE
Is it possible to declare a @field overload?

### ISSUE THREAD

**Issue by adriweb** [Benjamin-Dobell/IntelliJ-Luanalysis#39]
Context: I have a class where some fields are methods only set after init (`self.foobar = function(this, arg1, arg2) ... end`).

I have no choice but to annotate those with `@field` below the `@class` annotation, for instance:
`@field public foobar fun(self:MyClass, arg1:number, arg2:string):boolean`

The issue is that `arg2` is optional, and I can't seem to annotate that succesfully. If I do `arg2:string|nil` it expects a string or an **explicit** nil to be passed by the caller, and if I annotate with a whole alternative type to that function (like this: `@field public foobar (fun(self:MyClass, arg1:number, arg2:string):boolean)|(fun(self:MyClass, arg1:number):boolean)`), only one seems to be taken into account (the one with most args).

Thanks!

**Comment by Benjamin-Dobell** [comment]
You can avoid having to annotate an explicit field by doing:

```lua
---@class MyClass
local MyClass = {}

---@private
function MyClass:_init()
    ---@type MyClass
    local self = self

    ---@overload fun(a: number): number
    ---@param a number
    ---@param b number
    function self:myMethod(a, b)
    end
end
```

![Screen Shot 2021-01-12 at 1 42 36 pm](https://user-images.githubusercontent.com/482276/104262670-27ab2d00-54dc-11eb-99ae-3aba87008faa.png)

This means you don't have to duplicate the typing of the function, so this is my preferred approach.

That said, you can achieve a similar effect with callable types:

```lua
---@shape Overloaded
---@overload fun(self: MyClass, a: number): number
---@overload fun(self: MyClass, a: number, b: number): void

---@class MyClass
---@field myMethod Overloaded
local MyClass = {}
```

![Screen Shot 2021-01-12 at 1 45 42 pm](https://user-images.githubusercontent.com/482276/104262964-c46dca80-54dc-11eb-8caa-c93429252501.png)

Unfortunately, (at present) the callable shape approach doesn't auto-complete.

**Comment by adriweb** [comment]
Thanks!
