### ISSUE TITLE
string literal doesn't match string in multiple return value function annotation

### ISSUE THREAD

**Issue by adriweb** [Benjamin-Dobell/IntelliJ-Luanalysis#44]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version       | 2020.3.1 (IC-203.6682.168)
 Luanalysis version | 1.2.2 and also repro'd in latest master (now 5018fdb14e170ccfcdaa1359a4db2e662a8dbd27)
 OS                 | Linux Ubuntu 20.10

What are the steps to reproduce this issue?
------------------------------------------------

```lua
---@alias Handler fun(asyncCb:fun(success:boolean)): nil | true | (false,string)

---@type Handler
local myFunc1 = function(asyncCb) local msg = "asdf" return false, msg end

---@type Handler
local myFunc2 = function(asyncCb) return false, "asdf" end
```

What happens?
-------------
Error on the `"asdf"` string literal return:
`Type mismatch. Required: 'fun(asyncCb: fun(success: boolean)): ((false, string) | nil | true)' Found: 'fun(asyncCb: any): false, "asdf"'`

![image](https://user-images.githubusercontent.com/660896/106076794-487ba100-60de-11eb-9c30-8bd678c23a9e.png)

Note that the issue is specific to the case of multiple return values. No problem if there's only one return value, `"asdf"` will match `string`.

What were you expecting to happen?
-----------------------------------------
For "asdf" string to be treated as a string matching the annotation.

**Comment by Benjamin-Dobell** [comment]
Admittedly not sure when I fixed this, but I can no longer reproduce this with 1.2.3 or on `master`.

If I've made a mistake and you're still running into this please let me know and I'll reopen this.
