### ISSUE TITLE
Support of types with dots in their name

### ISSUE THREAD

**Issue by adriweb** [Benjamin-Dobell/IntelliJ-Luanalysis#5]
I have a rather large codebase using EmmyLua annotations, and some types have dots (`.`) in them.
It seems IntelliJ-Luanalysis doesn't support that.

This is quite useful when adding annotations to third-party libs for instance.

Example with a Penlight function:

```lua
--- Return a list of all file names within an array which match a pattern.
--- Raise dir and mask must be strings
--- @param filenames table|pl.List An array containing file names.
--- @param pattern string A shell pattern.
--- @return pl.List List of matching file names.
function dir.filter(filenames, pattern) end
```

This fails with the first @param type since the dots isn't recognized as part of the type name. Same with the return type.

**Comment by Benjamin-Dobell** [comment]
I've been using double underscore as a namespace token for my own purposes. Did this work with EmmyLua?

**Comment by adriweb** [comment]
Well it definitely worked at some point, because the annotations were working just fine, so I guess there was a regression some time? Not sure I could tell you when though :(

**Comment by Benjamin-Dobell** [comment]
I'd rather reserve `.` and `:` characters for returning the type of fields on another type. In the case of penlight, as long as the global type `pl` contains a `List` field, then it'll do what you want. However, you won't be able to do:

```lua
---@class pl.List
```

**Comment by adriweb** [comment]
Well that's annoying :( I would have lots of stuff to change, over multiple projects referencing each other etc. 

What are the downsides of allowing this character?
By the way, some of the types have multiple dots in them, kind of reflecting the package path.

**Comment by Benjamin-Dobell** [comment]
The downside is just:

> reserve `.`, `:` and `[]` tokens for returning the type of fields on another type

i.e. It makes much more sense that `.`, `:`, `[]` have the similar semantics in EmmyDoc as they do at runtime i.e. they're used as indexers, which is very useful functionality which is currently missing. It saves you repeating verbose types everywhere, say you've got:

```lua
---@class SomeClass
---@field thing number | string | thread | { [1]: "this" | "that", [2]: number }
```

When you want to refer to the type of `SomeClass.thing` you ought to be able to do just that i.e.

```
---@type SomeClass.thing
local aThing = someClass.thing
```

as opposed to:

```
---@type number | string | thread | { [1]: "this" | "that", [2]: number }
local aThing = someClass.thing
```

This neatly addresses https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/issues/6


However, if your penlight types are accurate, you won't actually need to change anything. Because penlight _does_ have `pl` type, and on it there is a field called `List`. So the following will work just fine:

```lua
---@type pl.List
local list = pl.List({1, 2, 3, 4})
```

**Comment by adriweb** [comment]
Right, that's fine maybe for the penlight example, but I do have lots of @class (and associated @type/param etc in various projects using the lib) declarations that are using it like this:

Let's say I have a `Message.lua` file just for annotations (so, dummy methods inside) for a DBus lib (I just took some parts for the example):
```lua
...

--------------------------------------------------------------------------------
---@class CompanyName.Bus.Message.Method
local Method = {}

---@param call CompanyName.Bus.Message.Method.Call
---@return CompanyName.Bus.Message.Method.Return
function Method.Return(call) end

--- @return CompanyName.Bus.Message.Method.Call
function Method.Call() end

--------------------------------------------------------------------------------
---@class CompanyName.Bus.Message.Signal
local Signal = {}

---@param member string The signal name
function Signal:setMember(member) end

---@param interface string The interface name
function Signal:setInterface(interface) end

---@return CompanyName.Bus.Object.Iterator
function Signal:begin() end

...

return {
  Method = Method,
  Signal = Signal,
  ...
}

```

For instance `CompanyName` doesn't actually represent anything, neither in annotations nor at runtime. It's just considered part of the class "name" (and what's used in the require).

Do I have no other way than changing all my annotations?

Looking at the code, I see it's `tag_class` has just an `ID`, corresponding to a regex with no possible dots, so I have no idea how it was working this whole time, must have been a bug :(

**Comment by Benjamin-Dobell** [comment]
> Looking at the code, I see it's tag_class has just an ID, corresponding to a regex with no possible dots, so I have no idea how it was working this whole time, must have been a bug :(

Yeah, to my knowledge it was never their intention to support periods in identifiers. I assume that it was working by accident. However, you're absolutely more than welcome to fork and make that change. You'll want to update:

https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/blob/master/src/main/java/com/tang/intellij/lua/doc.flex#L60
https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/blob/master/src/main/java/com/tang/intellij/lua/doc.bnf#L37

(Looks like I changed the former file in https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/commit/6562d4bdbbcb059dcf9651ab5a251c45f13752f4#diff-905bb6d2efe1bd61d74c550117c8f132L59-R59)

_I won't lie, GrammerKit is new to me, so why it was working in the past with periods in just one of those two locations is beyond me._

Anyway, once you've made those to changes use GrammarKit (https://github.com/JetBrains/Grammar-Kit) to regenerate, quite literally right-click the file in IntelliJ and it's in the context-menu. Then just build again and you're good to go.

However, as mentioned, I'm unfortunately not interested in making this change myself. I _absolutely_ understand why you want namespaces, having global types and no way of organising them is a recipe for disaster. However, I'd rather solve that issue with https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/issues/3, which needs further brainstorming. Maybe the solution could involve the use of periods to traverse consumer namespaces. However, as for allowing periods in names/identifiers themselves; I don't think I've ever seen a programming language that allows that. The token is usually reserved for indexing, which is how'd like to use the token.

**Comment by adriweb** [comment]
Yeah no worries, I understand your point of view.
It's just too bad that some colleagues and I ended up using this thinking it was a feature and not a bug.

**Comment by adriweb** [comment]
Heh, the VSCode EmmyLua plugin also supports dots:
![image](https://user-images.githubusercontent.com/660896/87563224-f8cb1000-c68c-11ea-9f2a-6e878136de7a.png)

**Comment by Benjamin-Dobell** [comment]
Yeah, impressively, the VSCode plugin actually uses the same code as the Java plugin! It's my intention to get a Luanalysis VSCode build up and running too.

**Comment by adriweb** [comment]
That's great :)

Just as confusing, `ID` is the same regex, so no idea why it works...

**Comment by adriweb** [comment]
I stumbled into more examples of annotations in other languages allowing periods in class names. For instance https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/server-response-time.js#L49-L54

Is there really no hope of ever getting this to work like in EmmyLua? :) (even though it was never intended, but still :P)

**Comment by baharclerode** [comment]
Instead of trying to retroactively reserve `.`, can `.` continue to be allowed as part of a class name and instead just reserve a different character for literal indexing (`#` comes to mind, which is used in java) ?
