### ISSUE TITLE
Disable return type inspections for .def.lua by default

### ISSUE THREAD

**Issue by Benjamin-Dobell** [Benjamin-Dobell/IntelliJ-Luanalysis#7]
Current work around is to manually follow the steps at:

https://gist.github.com/Benjamin-Dobell/990a65a19e09bf14a45576c7cbe3553e

**Comment by dcorbin** [comment]
I added my TTS-Types as it's own sub-module.  In that context, the scope needed to be `file:*.def.lua`

**Comment by Benjamin-Dobell** [comment]
Closed by 2bbff9bb03bbc734c93f20e5c851d1531ac51afb
