### ISSUE TITLE
Optional parameters?

### ISSUE THREAD

**Issue by K1ll3rM** [Benjamin-Dobell/IntelliJ-Luanalysis#74]
How do you define an optional parameter in the EmmyDoc?

**Comment by adriweb** [comment]
With `@overload`. Check for instance https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/blob/0b53e920af6f1e56a9e39f2ba57a77dde93055f7/src/test/resources/typeSafety/typeSafety.lua#L25

**Comment by K1ll3rM** [comment]
> With `@overload`. Check for instance
> 
> https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/blob/0b53e920af6f1e56a9e39f2ba57a77dde93055f7/src/test/resources/typeSafety/typeSafety.lua#L25

Thanks!
