### ISSUE TITLE
Infer specific type for function returning a string array

### ISSUE THREAD

**Issue by rillig** [Benjamin-Dobell/IntelliJ-Luanalysis#96]
Environment
--------------
   name   |   version  
----------|----------
 Luanalysis version | v1.3.0

What are the steps to reproduce this issue?
------------------------------------------------
~~~lua
local function string_array()
  return { "first", "second" }
end
~~~

What happens?
-------------
Luanalysis infers the return type to be `table`.

What were you expecting to happen?
-----------------------------------------
Luanalysis infers the return type to be `string[]`.

**Comment by Benjamin-Dobell** [comment]
This is intended. As it's written `string_array` does _not_ return `string[]`, and I wouldn't expect it to. Changing it to return a `string[]` is throwing away useful type information e.g.

```lua
---@alias Position "first" | "second"

---@param pos Position
local function wants_position(pos) end

local function not_a_string_array()
    return { "first", "second" }
end

wants_position(not_a_string_array()[1])
wants_position(not_a_string_array()[2])

---@return string[]
local function string_array()
    return { "first", "second" }
end

wants_position(string_array()[1]) -- Expect error
wants_position(string_array()[2]) -- Expect error
```

![Screen Shot 2021-08-21 at 5 39 34 pm](https://user-images.githubusercontent.com/482276/130314653-c8da4d8c-063c-41af-bfa9-dda7a51146f1.png)

In general if you want something to be a specific type, you ought to using type annotations.
